# Generated by Django 5.0.3 on 2024-03-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.AlterField(
            model_name='students',
            name='stuid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
