# Generated by Django 5.0.3 on 2024-03-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_students_id_alter_students_stuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='stuid',
            new_name='id',
        ),
    ]
