# Generated by Django 5.0.3 on 2024-03-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_stuid_students_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='stuid',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
